### ISSUE TITLE
I would like to know if azlocal is still supported 

### ISSUE THREAD

**Issue by quincy120** [localstack/azure-cli-local#1]
I am running into issues getting azlocal to run. I noticed that the last commit for this was done over 3 years ago, so I would like to know if this project is supported. I tried a simple vm list command and below is the issue I ran into. @dominikschubert 
@alexrashed

```bash
Quincys-Air:~ quincy$ azlocal vm list
Please run 'az login' to setup account.
Quincys-Air:~ quincy$ azlocal login
The command failed with an unexpected error. Here is the traceback:
invalid_instance: The authority you provided, https://localhost.localstack.cloud:12121/organizations, is not whitelisted. If it is indeed your legit customized domain name, you can turn off this check by passing in validate_authority=False
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/local/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
             ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/azure/cli/command_modules/profile/custom.py", line 139, in login
    subscriptions = profile.login(
                    ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/azure/cli/core/_profile.py", line 154, in login
    user_identity = identity.login_with_auth_code(scopes=scopes, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/azure/cli/core/auth/identity.py", line 153, in login_with_auth_code
    result = self._msal_app.acquire_token_interactive(
             ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/azure/cli/core/auth/identity.py", line 112, in _msal_app
    self._msal_app_instance = PublicClientApplication(self.client_id, **self._msal_app_kwargs)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/msal/application.py", line 1685, in __init__
    super(PublicClientApplication, self).__init__(
  File "/usr/local/lib/python3.11/site-packages/msal/application.py", line 533, in __init__
    self.authority = Authority(
                     ^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/msal/authority.py", line 103, in __init__
    raise ValueError(
ValueError: invalid_instance: The authority you provided, https://localhost.localstack.cloud:12121/organizations, is not whitelisted. If it is indeed your legit customized domain name, you can turn off this check by passing in validate_authority=False
```

**Comment by alexrashed** [comment]
Hi @quincy120!
Unfortunately this project is not maintained anymore, no.
This was only stated in the project description, which isn't too prominent:
> [unmaintained] Simple wrapper script to use Azure CLI with LocalStack 

I'll archive this repository to make this more explicit.
